#!/usr/bin/env python3

"""Tools for maintaining Grafana datasources."""

import argparse
import attr
import requests
import sys
from urllib.parse import ParseResult, urlparse


@attr.s
class BasicAuthCredentials(object):
    username = attr.ib()
    password = attr.ib()

    def to_json_dict(self):
        return {
            'basicAuth': True,
            'basicAuthUser': self.username,
            'basicAuthPassword': self.password
        }


@attr.s
class DataSource(object):
    """A data source for Grafana."""

    name = attr.ib()
    type = attr.ib()
    url = attr.ib()
    access = attr.ib()
    credentials = attr.ib()

    def to_json_dict(self):
        data = {
            'name': self.name,
            'type': self.type,
            'url': self.url,
            'access': self.access,
        }
        if self.credentials:
            data.update(self.credentials.to_json_dict())
        return data


@attr.s
class GrafanaAPI(object):
    """HTTP client for Grafana's API."""

    base_url = attr.ib()
    credentials = attr.ib()

    def update_datasource(self, data_source):
        return requests.post(
            '/'.join([self.base_url, 'datasources']),
            json=data_source.to_json_dict(),
            auth=(self.credentials.username, self.credentials.password)
        )


def make_parser():
    parser = argparse.ArgumentParser(prog='gfdatasource')
    parser.add_argument(
        '--grafana-url', type=urlparse, required=True,
        help="URL of Grafana API",
    )
    parser.add_argument(
        '--data-source-url', type=urlparse, required=True,
        help="URL of data source",
    )
    parser.add_argument(
        '--access', type=str, default='proxy',
        help="Type of access used by Grafana to the data source",
    )
    parser.add_argument(
        '--type', type=str, default='prometheus',
        help="The type of data source",
    )
    parser.add_argument(
        '--name', type=str, default='Prometheus',
        help="The name of the data source",
    )
    parser.add_argument(
        '--update-interval', type=int, default=10,
        help="How frequently to update Grafana, in seconds",
    )
    return parser


def _split_creds(url):
    creds = BasicAuthCredentials(url.username, url.password)
    netloc = url.netloc.split('@')[1] if '@' in url.netloc else url.netloc
    url = ParseResult(
        scheme=url.scheme,
        netloc=netloc,
        path=url.path,
        params=url.params,
        query=url.query,
        fragment=url.fragment,
    )
    return url.geturl(), creds


def main():
    parser = make_parser()
    opts = parser.parse_args(sys.argv[1:])
    grafana_url, grafana_creds = _split_creds(opts.grafana_url)
    grafana_api = GrafanaAPI(base_url=grafana_url, credentials=grafana_creds)
    datasource_url, datasource_creds = _split_creds(opts.data_source_url)
    datasource = DataSource(
        name=opts.name, type=opts.type, access=opts.access,
        url=datasource_url, credentials=datasource_creds,
    )
    while True:
        grafana_api.update_datasource(datasource)
        time.sleep(opts.update_interval)


main()
