FROM ddidier/sphinx-doc

WORKDIR /doc

COPY . .

RUN pip3 install -r docs/requirements.txt && \
    apt update && apt install -y linkchecker && \
    python3 setup.py install && \
    cd docs && mkdir _static && make html && \
    cd build/html/_static/fonts/RobotoSlab && \
    ln -s roboto-slab-v7-regular.eot roboto-slab.eot


CMD ["python", "-m", "http.server", "8000"]
